"""Add priority classification fields to events table

Revision ID: ad00a873400b
Revises: 7fe73f0ad0ce
Create Date: 2025-07-30 21:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ad00a873400b'
down_revision: Union[str, None] = '7fe73f0ad0ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add priority classification fields to events table
    op.add_column('events', sa.Column('priority_level', sa.Integer(), nullable=False, server_default='3'))
    op.add_column('events', sa.Column('priority_confidence', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('events', sa.Column('classification_method', sa.String(length=50), nullable=False, server_default='manual'))
    
    # Create index on priority_level for efficient querying
    op.create_index(op.f('ix_events_priority_level'), 'events', ['priority_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove priority classification fields from events table
    op.drop_index(op.f('ix_events_priority_level'), table_name='events')
    op.drop_column('events', 'classification_method')
    op.drop_column('events', 'priority_confidence')
    op.drop_column('events', 'priority_level')
    # ### end Alembic commands ###
